# Generated by Django 4.1 on 2022-10-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliniq', '0002_gerent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialiste',
            name='spécialité',
            field=models.CharField(choices=[('Pediatrie', 'PT'), ('Dentiste', 'DT'), ('Dermatologist', 'Dr')], max_length=200),
        ),
    ]
