# Generated by Django 4.1 on 2022-10-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliniq', '0003_alter_specialiste_spécialité'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialiste',
            name='spécialité',
            field=models.CharField(choices=[('Pediatrie', 'Pediatrie'), ('Dentiste', 'Dentiste'), ('Dermatologist', 'Dermatologist')], max_length=200),
        ),
    ]
