# Generated by Django 4.1 on 2022-10-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliniq', '0004_alter_specialiste_spécialité'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='specialiste',
            field=models.ManyToManyField(related_name='patient', to='cliniq.specialiste'),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='spécialiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sp_rdv', to='cliniq.specialiste'),
        ),
    ]
