# Generated by Django 4.1 on 2022-10-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliniq', '0005_patient_specialiste_alter_rdv_spécialiste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='specialiste',
        ),
        migrations.AddField(
            model_name='specialiste',
            name='patient',
            field=models.ManyToManyField(related_name='patient', to='cliniq.patient'),
        ),
    ]
