# Generated by Django 4.1 on 2022-10-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliniq', '0006_remove_patient_specialiste_specialiste_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialiste',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='specialiste',
            field=models.ManyToManyField(related_name='specialiste', to='cliniq.specialiste'),
        ),
    ]
