# Generated by Django 4.1 on 2022-10-25 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliniq', '0007_remove_specialiste_patient_patient_specialiste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='specialiste',
        ),
    ]
